import { Book } from "../interfaces/book.interface";

export const books: Book[] = [
  {
    id: '0b5ae796-a5ce-44e7-9214-c930ed455541',
    name: 'A monster wants to eat me',
    img: 'assets/img/category-manga.png',
    distance: 1.5,
    userId: 1,
    userUserName: 'Maria',
    review: 4.5,
    author: 'John Doe',
    bookStatus: 'Usado como nuevo',
    cover: 'Blanda',
    sinceTime: '45m',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 1,
    name: '1984',
    img: 'assets/img/category-clasicos.png',
    distance: 2,

    userId: 2,
    userUserName: 'Luis',
    review: 3,
    author: 'George Orwell',
    bookStatus: 'Usado como nuevo',
    cover: 'Dura',
    sinceTime: '5m',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 2,
    name: 'Filosofix',
    img: 'assets/img/category-filosofia.png',
    distance: 5,

    userId: 3,
    userUserName: 'Ana',
    review: 3,
    author: 'Javier Ruiz',
    bookStatus: 'Usado como nuevo',
    cover: 'Dura',
    sinceTime: '1d',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 3,
    name: 'One Piece VOL. I',
    img: 'assets/img/one-piece.png',
    distance: 1.5,

    userId: 4,
    userUserName: 'Carlos',
    review: 5,
    author: 'Eiichiro Oda',
    bookStatus: 'Usado como nuevo',
    cover: 'Blanda',
    sinceTime: '15m',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 4,
    name: 'Los Renegados',
    img: 'assets/img/renegados.png',
    distance: 1.5,

    userId: 4,
    userUserName: 'Carlos',
    review: 3,
    author: 'Marrisa Meyer',
    bookStatus: 'Usado como nuevo',
    cover: 'Dura',
    sinceTime: '1h',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 5,
    name: 'Bajo la misma estrella',
    img: 'assets/img/bajolamismaestrella.png',
    distance: 1.5,

    userId: 4,
    userUserName: 'Carlos',
    review: 5,
    author: 'John Green',
    bookStatus: 'Usado como nuevo',
    cover: 'Dura',
    sinceTime: '5m',
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 6, name: 'The drama with doomsday', img: 'assets/img/category-drama.png', distance: 3, sinceTime: '2m', userUserName: 'Ana', userId: 3,
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 7, name: 'Charly y la fabrica de chocolate', img: 'assets/img/category-infantil.png', distance: 4, sinceTime: '2h', userUserName: 'Ana', userId: 3,
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 8, name: 'Night of terror', img: 'assets/img/category-terror.png', distance: 10, sinceTime: '10m', userUserName: 'Maria', userId: 1,
    qrImg: "assets/img/qr-code.png",
    price: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
]

export const tradeBooks: Book[] = [
  {
    id: 0, name: 'The drama with doomsday', img: 'assets/img/category-drama.png', distance: 3, sinceTime: '2m', userUserName: 'Santiago',
    qrImg: "",
    price: 0,
    userId: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 1, name: 'Charly y la fabrica de chocolate', img: 'assets/img/category-infantil.png', distance: 4, sinceTime: '2h', userUserName: 'Margaret',
    qrImg: "",
    price: 0,
    userId: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
  {
    id: 2, name: 'Night of terror', img: 'assets/img/category-terror.png', distance: 10, sinceTime: '10m', userUserName: 'Fabio',
    qrImg: "",
    price: 0,
    userId: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
]

export const acceptedBooks: Book[] = [
  {
    id: 0, name: 'Charly y la fabrica de chocolate', img: 'assets/img/category-infantil.png', distance: 4, sinceTime: '1d', userId: 1, userUserName: 'Maria',
    qrImg: "",
    price: 0,
    requestUsersIds: [],
    review: 0,
    author: "",
    bookStatus: "",
    cover: "",
    soldOut: false,
    categories: [],
    description: ""
  },
]