import { ForumComment } from '../interfaces/forum-comment.interface';

export const forumComments: ForumComment[] = [
  // Forum 0
  {
    id: 0,
    createdAt: new Date('2024-11-01T10:15:00'),
    comment: 'Totalmente de acuerdo con lo planteado.',
    forumId: 0,
    userId: 1,
    userName: 'Camila Torres',
    userImg: 'assets/img/users/camila.png',
  },
  {
    id: 1,
    createdAt: new Date('2024-11-01T10:17:00'),
    comment: 'Creo que deberíamos reunirnos para discutirlo mejor.',
    forumId: 0,
    userId: 2,
    userName: 'Jorge Méndez',
    userImg: 'assets/img/users/jorge.png',
  },
  {
    id: 2,
    createdAt: new Date('2024-11-01T10:20:00'),
    comment: 'Estoy revisando un par de ideas que podrían servir.',
    forumId: 0,
    userId: 3,
    userName: 'Laura Pérez',
    userImg: 'assets/img/users/laura.png',
  },
  {
    id: 3,
    createdAt: new Date('2024-11-01T10:22:00'),
    comment: 'Gracias por compartir esto, fue muy útil.',
    forumId: 0,
    userId: 1,
    userName: 'Camila Torres',
    userImg: 'assets/img/users/camila.png',
  },
  {
    id: 4,
    createdAt: new Date('2024-11-01T10:25:00'),
    comment: '¿Podrías elaborar más tu punto?',
    forumId: 0,
    userId: 4,
    userName: 'David Ruiz',
    userImg: 'assets/img/users/david.png',
  },

  // Forum 1
  {
    id: 5,
    createdAt: new Date('2024-11-02T09:10:00'),
    comment: 'Este tema es muy interesante, gracias por abrirlo.',
    forumId: 1,
    userId: 2,
    userName: 'Jorge Méndez',
    userImg: 'assets/img/users/jorge.png',
  },
  {
    id: 6,
    createdAt: new Date('2024-11-02T09:15:00'),
    comment: 'Tengo una experiencia similar que me gustaría compartir.',
    forumId: 1,
    userId: 5,
    userName: 'Andrea Salazar',
    userImg: 'assets/img/users/andrea.png',
  },
  {
    id: 7,
    createdAt: new Date('2024-11-02T09:20:00'),
    comment: 'Podríamos crear una guía juntos.',
    forumId: 1,
    userId: 6,
    userName: 'Carlos Díaz',
    userImg: 'assets/img/users/carlos.png',
  },
  {
    id: 8,
    createdAt: new Date('2024-11-02T09:22:00'),
    comment: '¿Alguien tiene referencias sobre esto?',
    forumId: 1,
    userId: 3,
    userName: 'Laura Pérez',
    userImg: 'assets/img/users/laura.png',
  },
  {
    id: 9,
    createdAt: new Date('2024-11-02T09:25:00'),
    comment: 'Lo revisé y me parece correcto.',
    forumId: 1,
    userId: 4,
    userName: 'David Ruiz',
    userImg: 'assets/img/users/david.png',
  },

  // Forum 2
  {
    id: 10,
    createdAt: new Date('2024-11-03T11:30:00'),
    comment: '¿Alguien ha probado esta técnica?',
    forumId: 2,
    userId: 6,
    userName: 'Carlos Díaz',
    userImg: 'assets/img/users/carlos.png',
  },
  {
    id: 11,
    createdAt: new Date('2024-11-03T11:33:00'),
    comment: 'Sí, funciona bastante bien en mi experiencia.',
    forumId: 2,
    userId: 5,
    userName: 'Andrea Salazar',
    userImg: 'assets/img/users/andrea.png',
  },
  {
    id: 12,
    createdAt: new Date('2024-11-03T11:35:00'),
    comment: '¿Dónde encontraste esa información?',
    forumId: 2,
    userId: 1,
    userName: 'Camila Torres',
    userImg: 'assets/img/users/camila.png',
  },
  {
    id: 13,
    createdAt: new Date('2024-11-03T11:38:00'),
    comment: 'Podemos organizar un documento con lo aprendido.',
    forumId: 2,
    userId: 2,
    userName: 'Jorge Méndez',
    userImg: 'assets/img/users/jorge.png',
  },
  {
    id: 14,
    createdAt: new Date('2024-11-03T11:42:00'),
    comment: 'Perfecto, estaré pendiente de lo que compartan.',
    forumId: 2,
    userId: 3,
    userName: 'Laura Pérez',
    userImg: 'assets/img/users/laura.png',
  },
];
